export const championList = [
  { kor: '가렌', eng: 'Garen', id: 86 },
  { kor: '갈리오', eng: 'Galio', id: 3 },
  { kor: '갱플랭크', eng: 'Gangplank', id: 41 },
  { kor: '그라가스', eng: 'Gragas', id: 79 },
  { kor: '그레이브즈', eng: 'Graves', id: 104 },
  { kor: '그웬', eng: 'Gwen', id: 887 },
  { kor: '나르', eng: 'Gnar', id: 150 },
  { kor: '나미', eng: 'Nami', id: 267 },
  { kor: '나서스', eng: 'Nasus', id: 75 },
  { kor: '노틸러스', eng: 'Nautilus', id: 111 },
  { kor: '녹턴', eng: 'Nocturne', id: 56 },
  { kor: '누누와 월럼프', eng: 'Nunu', id: 20 },
  { kor: '니달리', eng: 'Nidalee', id: 76 },
  { kor: '니코', eng: 'Neeko', id: 518 },
  { kor: '닐라', eng: 'Nilah', id: 895 },
  { kor: '다리우스', eng: 'Darius', id: 122 },
  { kor: '다이애나', eng: 'Diana', id: 131 },
  { kor: '드레이븐', eng: 'Draven', id: 119 },
  { kor: '라이즈', eng: 'Ryze', id: 13 },
  { kor: '라칸', eng: 'Rakan', id: 497 },
  { kor: '람머스', eng: 'Rammus', id: 33 },
  { kor: '럭스', eng: 'Lux', id: 99 },
  { kor: '럼블', eng: 'Rumble', id: 68 },
  { kor: '레나타 글라스크', eng: 'Renata', id: 888 },
  { kor: '레넥톤', eng: 'Renekton', id: 58 },
  { kor: '레오나', eng: 'Leona', id: 89 },
  { kor: '렉사이', eng: 'RekSai', id: 421 },
  { kor: '렐', eng: 'Rell', id: 526 },
  { kor: '렝가', eng: 'Rengar', id: 107 },
  { kor: '루시안', eng: 'Lucian', id: 236 },
  { kor: '룰루', eng: 'Lulu', id: 117 },
  { kor: '르블랑', eng: 'Leblanc', id: 7 },
  { kor: '리 신', eng: 'LeeSin', id: 64 },
  { kor: '리븐', eng: 'Riven', id: 92 },
  { kor: '리산드라', eng: 'Lissandra', id: 127 },
  { kor: '릴리아', eng: 'Lillia', id: 876 },
  { kor: '마스터 이', eng: 'MasterYi', id: 11 },
  { kor: '마오카이', eng: 'Maokai', id: 57 },
  { kor: '말자하', eng: 'Malzahar', id: 90 },
  { kor: '말파이트', eng: 'Malphite', id: 54 },
  { kor: '모데카이저', eng: 'Mordekaiser', id: 82 },
  { kor: '모르가나', eng: 'Morgana', id: 25 },
  { kor: '문도 박사', eng: 'DrMundo', id: 36 },
  { kor: '미스 포츈', eng: 'MissFortune', id: 21 },
  { kor: '바드', eng: 'Bard', id: 432 },
  { kor: '바루스', eng: 'Varus', id: 110 },
  { kor: '바이', eng: 'Vi', id: 254 },
  { kor: '베이가', eng: 'Veigar', id: 45 },
  { kor: '베인', eng: 'Vayne', id: 67 },
  { kor: '벡스', eng: 'Vex', id: 711 },
  { kor: '벨베스', eng: 'Belveth', id: 200 },
  { kor: '벨코즈', eng: 'Velkoz', id: 161 },
  { kor: '볼리베어', eng: 'Volibear', id: 106 },
  { kor: '브라움', eng: 'Braum', id: 201 },
  { kor: '브랜드', eng: 'Brand', id: 63 },
  { kor: '블라디미르', eng: 'Vladimir', id: 8 },
  { kor: '블리츠크랭크', eng: 'Blitzcrank', id: 53 },
  { kor: '비에고', eng: 'Viego', id: 234 },
  { kor: '빅토르', eng: 'Viktor', id: 112 },
  { kor: '뽀삐', eng: 'Poppy', id: 78 },
  { kor: '사미라', eng: 'Samira', id: 360 },
  { kor: '사이온', eng: 'Sion', id: 14 },
  { kor: '사일러스', eng: 'Sylas', id: 517 },
  { kor: '샤코', eng: 'Shaco', id: 35 },
  { kor: '세나', eng: 'Senna', id: 235 },
  { kor: '세라핀', eng: 'Seraphine', id: 147 },
  { kor: '세주아니', eng: 'Sejuani', id: 113 },
  { kor: '세트', eng: 'Sett', id: 875 },
  { kor: '소나', eng: 'Sona', id: 37 },
  { kor: '소라카', eng: 'Soraka', id: 16 },
  { kor: '쉔', eng: 'Shen', id: 98 },
  { kor: '쉬바나', eng: 'Shyvana', id: 102 },
  { kor: '스웨인', eng: 'Swain', id: 50 },
  { kor: '스카너', eng: 'Skarner', id: 72 },
  { kor: '시비르', eng: 'Sivir', id: 15 },
  { kor: '신 짜오', eng: 'XinZhao', id: 5 },
  { kor: '신드라', eng: 'Syndra', id: 134 },
  { kor: '신지드', eng: 'Singed', id: 27 },
  { kor: '쓰레쉬', eng: 'Thresh', id: 412 },
  { kor: '아리', eng: 'Ahri', id: 103 },
  { kor: '아무무', eng: 'Amumu', id: 32 },
  { kor: '아우렐리온 솔', eng: 'AurelionSol', id: 136 },
  { kor: '아이번', eng: 'Ivern', id: 427 },
  { kor: '아지르', eng: 'Azir', id: 268 },
  { kor: '아칼리', eng: 'Akali', id: 84 },
  { kor: '아크샨', eng: 'Akshan', id: 166 },
  { kor: '아트록스', eng: 'Aatrox', id: 266 },
  { kor: '아펠리오스', eng: 'Aphelios', id: 523 },
  { kor: '알리스타', eng: 'Alistar', id: 12 },
  { kor: '애니', eng: 'Annie', id: 1 },
  { kor: '애니비아', eng: 'Anivia', id: 34 },
  { kor: '애쉬', eng: 'Ashe', id: 22 },
  { kor: '야스오', eng: 'Yasuo', id: 157 },
  { kor: '에코', eng: 'Ekko', id: 245 },
  { kor: '엘리스', eng: 'Elise', id: 60 },
  { kor: '오공', eng: 'MonkeyKing', id: 62 },
  { kor: '오른', eng: 'Ornn', id: 516 },
  { kor: '오리아나', eng: 'Orianna', id: 61 },
  { kor: '올라프', eng: 'Olaf', id: 2 },
  { kor: '요네', eng: 'Yone', id: 777 },
  { kor: '요릭', eng: 'Yorick', id: 83 },
  { kor: '우디르', eng: 'Udyr', id: 77 },
  { kor: '우르곳', eng: 'Urgot', id: 6 },
  { kor: '워윅', eng: 'Warwick', id: 19 },
  { kor: '유미', eng: 'Yuumi', id: 350 },
  { kor: '이렐리아', eng: 'Irelia', id: 39 },
  { kor: '이블린', eng: 'Evelynn', id: 28 },
  { kor: '이즈리얼', eng: 'Ezreal', id: 81 },
  { kor: '일라오이', eng: 'Illaoi', id: 420 },
  { kor: '자르반 4세', eng: 'JarvanIV', id: 59 },
  { kor: '자야', eng: 'Xayah', id: 498 },
  { kor: '자이라', eng: 'Zyra', id: 143 },
  { kor: '자크', eng: 'Zac', id: 154 },
  { kor: '잔나', eng: 'Janna', id: 40 },
  { kor: '잭스', eng: 'Jax', id: 24 },
  { kor: '제드', eng: 'Zed', id: 238 },
  { kor: '제라스', eng: 'Xerath', id: 101 },
  { kor: '제리', eng: 'Zeri', id: 221 },
  { kor: '제이스', eng: 'Jayce', id: 126 },
  { kor: '조이', eng: 'Zoe', id: 142 },
  { kor: '직스', eng: 'Ziggs', id: 115 },
  { kor: '진', eng: 'Jhin', id: 202 },
  { kor: '질리언', eng: 'Zilean', id: 26 },
  { kor: '징크스', eng: 'Jinx', id: 222 },
  { kor: '초가스', eng: 'Chogath', id: 31 },
  { kor: '카르마', eng: 'Karma', id: 43 },
  { kor: '카밀', eng: 'Camille', id: 164 },
  { kor: '카사딘', eng: 'Kassadin', id: 38 },
  { kor: '카서스', eng: 'Karthus', id: 30 },
  { kor: '카시오페아', eng: 'Cassiopeia', id: 69 },
  { kor: '카이사', eng: 'Kaisa', id: 145 },
  { kor: '카직스', eng: 'Khazix', id: 121 },
  { kor: '카타리나', eng: 'Katarina', id: 55 },
  { kor: '칼리스타', eng: 'Kalista', id: 429 },
  { kor: '케넨', eng: 'Kennen', id: 85 },
  { kor: '케이틀린', eng: 'Caitlyn', id: 51 },
  { kor: '케인', eng: 'Kayn', id: 141 },
  { kor: '케일', eng: 'Kayle', id: 10 },
  { kor: '코그모', eng: 'KogMaw', id: 96 },
  { kor: '코르키', eng: 'Corki', id: 42 },
  { kor: '퀸', eng: 'Quinn', id: 133 },
  { kor: '클레드', eng: 'Kled', id: 240 },
  { kor: '키아나', eng: 'Qiyana', id: 246 },
  { kor: '킨드레드', eng: 'Kindred', id: 203 },
  { kor: '타릭', eng: 'Taric', id: 44 },
  { kor: '탈론', eng: 'Talon', id: 91 },
  { kor: '탈리야', eng: 'Taliyah', id: 163 },
  { kor: '탐 켄치', eng: 'TahmKench', id: 223 },
  { kor: '트런들', eng: 'Trundle', id: 48 },
  { kor: '트리스타나', eng: 'Tristana', id: 18 },
  { kor: '트린다미어', eng: 'Tryndamere', id: 23 },
  { kor: '트위스티드 페이트', eng: 'TwistedFate', id: 4 },
  { kor: '트위치', eng: 'Twitch', id: 29 },
  { kor: '티모', eng: 'Teemo', id: 17 },
  { kor: '파이크', eng: 'Pyke', id: 555 },
  { kor: '판테온', eng: 'Pantheon', id: 80 },
  { kor: '피들스틱', eng: 'Fiddlesticks', id: 9 },
  { kor: '피오라', eng: 'Fiora', id: 114 },
  { kor: '피즈', eng: 'Fizz', id: 105 },
  { kor: '하이머딩거', eng: 'Heimerdinger', id: 74 },
  { kor: '헤카림', eng: 'Hecarim', id: 120 },
];

export const championObject: any = {
  1: { kor: '애니', eng: 'Annie' },
  2: { kor: '올라프', eng: 'Olaf' },
  3: { kor: '갈리오', eng: 'Galio' },
  4: { kor: '트위스티드 페이트', eng: 'TwistedFate' },
  5: { kor: '신 짜오', eng: 'XinZhao' },
  6: { kor: '우르곳', eng: 'Urgot' },
  7: { kor: '르블랑', eng: 'Leblanc' },
  8: { kor: '블라디미르', eng: 'Vladimir' },
  9: { kor: '피들스틱', eng: 'Fiddlesticks' },
  10: { kor: '케일', eng: 'Kayle' },
  11: { kor: '마스터 이', eng: 'MasterYi' },
  12: { kor: '알리스타', eng: 'Alistar' },
  13: { kor: '라이즈', eng: 'Ryze' },
  14: { kor: '사이온', eng: 'Sion' },
  15: { kor: '시비르', eng: 'Sivir' },
  16: { kor: '소라카', eng: 'Soraka' },
  17: { kor: '티모', eng: 'Teemo' },
  18: { kor: '트리스타나', eng: 'Tristana' },
  19: { kor: '워윅', eng: 'Warwick' },
  20: { kor: '누누와 월럼프', eng: 'Nunu' },
  21: { kor: '미스 포츈', eng: 'MissFortune' },
  22: { kor: '애쉬', eng: 'Ashe' },
  23: { kor: '트린다미어', eng: 'Tryndamere' },
  24: { kor: '잭스', eng: 'Jax' },
  25: { kor: '모르가나', eng: 'Morgana' },
  26: { kor: '질리언', eng: 'Zilean' },
  27: { kor: '신지드', eng: 'Singed' },
  28: { kor: '이블린', eng: 'Evelynn' },
  29: { kor: '트위치', eng: 'Twitch' },
  30: { kor: '카서스', eng: 'Karthus' },
  31: { kor: '초가스', eng: 'Chogath' },
  32: { kor: '아무무', eng: 'Amumu' },
  33: { kor: '람머스', eng: 'Rammus' },
  34: { kor: '애니비아', eng: 'Anivia' },
  35: { kor: '샤코', eng: 'Shaco' },
  36: { kor: '문도 박사', eng: 'DrMundo' },
  37: { kor: '소나', eng: 'Sona' },
  38: { kor: '카사딘', eng: 'Kassadin' },
  39: { kor: '이렐리아', eng: 'Irelia' },
  40: { kor: '잔나', eng: 'Janna' },
  41: { kor: '갱플랭크', eng: 'Gangplank' },
  42: { kor: '코르키', eng: 'Corki' },
  43: { kor: '카르마', eng: 'Karma' },
  44: { kor: '타릭', eng: 'Taric' },
  45: { kor: '베이가', eng: 'Veigar' },
  48: { kor: '트런들', eng: 'Trundle' },
  50: { kor: '스웨인', eng: 'Swain' },
  51: { kor: '케이틀린', eng: 'Caitlyn' },
  53: { kor: '블리츠크랭크', eng: 'Blitzcrank' },
  54: { kor: '말파이트', eng: 'Malphite' },
  55: { kor: '카타리나', eng: 'Katarina' },
  56: { kor: '녹턴', eng: 'Nocturne' },
  57: { kor: '마오카이', eng: 'Maokai' },
  58: { kor: '레넥톤', eng: 'Renekton' },
  59: { kor: '자르반 4세', eng: 'JarvanIV' },
  60: { kor: '엘리스', eng: 'Elise' },
  61: { kor: '오리아나', eng: 'Orianna' },
  62: { kor: '오공', eng: 'MonkeyKing' },
  63: { kor: '브랜드', eng: 'Brand' },
  64: { kor: '리 신', eng: 'LeeSin' },
  67: { kor: '베인', eng: 'Vayne' },
  68: { kor: '럼블', eng: 'Rumble' },
  69: { kor: '카시오페아', eng: 'Cassiopeia' },
  72: { kor: '스카너', eng: 'Skarner' },
  74: { kor: '하이머딩거', eng: 'Heimerdinger' },
  75: { kor: '나서스', eng: 'Nasus' },
  76: { kor: '니달리', eng: 'Nidalee' },
  77: { kor: '우디르', eng: 'Udyr' },
  78: { kor: '뽀삐', eng: 'Poppy' },
  79: { kor: '그라가스', eng: 'Gragas' },
  80: { kor: '판테온', eng: 'Pantheon' },
  81: { kor: '이즈리얼', eng: 'Ezreal' },
  82: { kor: '모데카이저', eng: 'Mordekaiser' },
  83: { kor: '요릭', eng: 'Yorick' },
  84: { kor: '아칼리', eng: 'Akali' },
  85: { kor: '케넨', eng: 'Kennen' },
  86: { kor: '가렌', eng: 'Garen' },
  89: { kor: '레오나', eng: 'Leona' },
  90: { kor: '말자하', eng: 'Malzahar' },
  91: { kor: '탈론', eng: 'Talon' },
  92: { kor: '리븐', eng: 'Riven' },
  96: { kor: '코그모', eng: 'KogMaw' },
  98: { kor: '쉔', eng: 'Shen' },
  99: { kor: '럭스', eng: 'Lux' },
  101: { kor: '제라스', eng: 'Xerath' },
  102: { kor: '쉬바나', eng: 'Shyvana' },
  103: { kor: '아리', eng: 'Ahri' },
  104: { kor: '그레이브즈', eng: 'Graves' },
  105: { kor: '피즈', eng: 'Fizz' },
  106: { kor: '볼리베어', eng: 'Volibear' },
  107: { kor: '렝가', eng: 'Rengar' },
  110: { kor: '바루스', eng: 'Varus' },
  111: { kor: '노틸러스', eng: 'Nautilus' },
  112: { kor: '빅토르', eng: 'Viktor' },
  113: { kor: '세주아니', eng: 'Sejuani' },
  114: { kor: '피오라', eng: 'Fiora' },
  115: { kor: '직스', eng: 'Ziggs' },
  117: { kor: '룰루', eng: 'Lulu' },
  119: { kor: '드레이븐', eng: 'Draven' },
  120: { kor: '헤카림', eng: 'Hecarim' },
  121: { kor: '카직스', eng: 'Khazix' },
  122: { kor: '다리우스', eng: 'Darius' },
  126: { kor: '제이스', eng: 'Jayce' },
  127: { kor: '리산드라', eng: 'Lissandra' },
  131: { kor: '다이애나', eng: 'Diana' },
  133: { kor: '퀸', eng: 'Quinn' },
  134: { kor: '신드라', eng: 'Syndra' },
  136: { kor: '아우렐리온 솔', eng: 'AurelionSol' },
  141: { kor: '케인', eng: 'Kayn' },
  142: { kor: '조이', eng: 'Zoe' },
  143: { kor: '자이라', eng: 'Zyra' },
  145: { kor: '카이사', eng: 'Kaisa' },
  147: { kor: '세라핀', eng: 'Seraphine' },
  150: { kor: '나르', eng: 'Gnar' },
  154: { kor: '자크', eng: 'Zac' },
  157: { kor: '야스오', eng: 'Yasuo' },
  161: { kor: '벨코즈', eng: 'Velkoz' },
  163: { kor: '탈리야', eng: 'Taliyah' },
  164: { kor: '카밀', eng: 'Camille' },
  166: { kor: '아크샨', eng: 'Akshan' },
  200: { kor: '벨베스', eng: 'Belveth' },
  201: { kor: '브라움', eng: 'Braum' },
  202: { kor: '진', eng: 'Jhin' },
  203: { kor: '킨드레드', eng: 'Kindred' },
  221: { kor: '제리', eng: 'Zeri' },
  222: { kor: '징크스', eng: 'Jinx' },
  223: { kor: '탐 켄치', eng: 'TahmKench' },
  234: { kor: '비에고', eng: 'Viego' },
  235: { kor: '세나', eng: 'Senna' },
  236: { kor: '루시안', eng: 'Lucian' },
  238: { kor: '제드', eng: 'Zed' },
  240: { kor: '클레드', eng: 'Kled' },
  245: { kor: '에코', eng: 'Ekko' },
  246: { kor: '키아나', eng: 'Qiyana' },
  254: { kor: '바이', eng: 'Vi' },
  266: { kor: '아트록스', eng: 'Aatrox' },
  267: { kor: '나미', eng: 'Nami' },
  268: { kor: '아지르', eng: 'Azir' },
  350: { kor: '유미', eng: 'Yuumi' },
  360: { kor: '사미라', eng: 'Samira' },
  412: { kor: '쓰레쉬', eng: 'Thresh' },
  420: { kor: '일라오이', eng: 'Illaoi' },
  421: { kor: '렉사이', eng: 'RekSai' },
  427: { kor: '아이번', eng: 'Ivern' },
  429: { kor: '칼리스타', eng: 'Kalista' },
  432: { kor: '바드', eng: 'Bard' },
  497: { kor: '라칸', eng: 'Rakan' },
  498: { kor: '자야', eng: 'Xayah' },
  516: { kor: '오른', eng: 'Ornn' },
  517: { kor: '사일러스', eng: 'Sylas' },
  518: { kor: '니코', eng: 'Neeko' },
  523: { kor: '아펠리오스', eng: 'Aphelios' },
  526: { kor: '렐', eng: 'Rell' },
  555: { kor: '파이크', eng: 'Pyke' },
  711: { kor: '벡스', eng: 'Vex' },
  777: { kor: '요네', eng: 'Yone' },
  875: { kor: '세트', eng: 'Sett' },
  876: { kor: '릴리아', eng: 'Lillia' },
  887: { kor: '그웬', eng: 'Gwen' },
  888: { kor: '레나타 글라스크', eng: 'Renata' },
  895: { kor: '닐라', eng: 'Nilah' },
};
